config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/save" => "bookmarks#save"

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"

  resources :devices do
    resources :browser_windows do
      resources :browser_tabs
    end
  end

  resources :bookmarks, except: [:index, :search]
  get 'bookmarks' => 'bookmarks#index'
  get 'bookmarks_search' => 'bookmarks#search', as: :bookmarks_search

  resources :tags
  get 'tags_search' => 'tags#search', as: :tags_search

  resources :search, only: [:index]
  get '/search/search' => 'search#search', as: :multi_search, :constraints => { :only_ajax => true }

  root 'search#index'
  get ':user' => 'bookmarks#index', as: :user_bookmarks
end

app/models/device.rb
class Device < ActiveRecord::Base
	belongs_to :user
	has_many :browser_windows
	has_many :browser_tabs, through: :browser_window

	default_scope { order(created_at: :asc) }

	def owner
		user
	end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
	def index
		authorize Device
		@devices = current_user.devices
	end

	def show
		@device = Device.find(params[:id])
		authorize @device
	end

	def new
		authorize Device
		@device = Device.new
		@devices = current_user.devices
	end

	def create
		authorize Device
		device = Device.create(device_params.merge({user: current_user}))
		redirect_to device
	end

	def update
		device = Device.find(params[:id])
		authorize device
		device.update!(device_params.merge({user: current_user}))
		redirect_to device
	end

	def edit
		@device = Device.find(params[:id])
		authorize @device
		@devices = current_user.devices
	end

	private
		def device_params
      params.require(:device).permit(:name)
    end
end

app/views/devices/_form.html.slim
=form_for @device do |f|
	=f.label :name
	=f.text_field :name
	=f.submit

app/views/devices/edit.html.slim
h1 ="Edit device: #{@device.name}"
= render 'form'

hr
h2 Existing Devices
- unless @devices.blank?
	ol
		- @devices.each do |d|
			li
				=link_to d, data: {'device-id': d.id} do
					span =d.name
					em =" (#{d.browser_windows.count})"

app/views/devices/index.html.slim
h1 Device List
=link_to "create new device", new_device_path
hr
- unless @devices.blank?
	ol
		- @devices.each do |d|
			li
				=link_to d, data: {'device-id': d.id } do
					span =d.name
					em =" (#{d.browser_windows.count})"

app/views/devices/new.html.slim
h1 Add new device
= render 'form'

hr
h2 Existing Devices
- unless @devices.blank?
	ol
		- @devices.each do |d|
			li
				=link_to d, data: {'device-id': d.id} do
					span =d.name
					em =" (#{d.browser_windows.count})"

app/views/devices/show.html.slim
h1 ="Device: #{@device.name}"
=link_to '[Edit]', edit_device_path(@device)
=" | "
=link_to '[New Window]', new_device_browser_window_path(@device)
hr
h2 ="#{@device.name} Windows:"

- windows = @device.browser_windows
- unless windows.blank?
	ol
		- windows.sort.each do |bw|
			li
				= link_to device_browser_window_path(@device, bw.id), data: {'browser-window-id': bw.id} do
					em ="(#{bw.browser_tabs.count})"
					| &mdash;
					span =bw.private?