config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/save" => "bookmarks#save"

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"

  resources :devices do
    resources :browser_windows do
      resources :browser_tabs
    end
  end

  resources :bookmarks, except: [:index, :search]
  get 'bookmarks' => 'bookmarks#index'
  get 'bookmarks_search' => 'bookmarks#search', as: :bookmarks_search

  resources :tags
  get 'tags_search' => 'tags#search', as: :tags_search

  resources :search, only: [:index]
  get '/search/search' => 'search#search', as: :multi_search, :constraints => { :only_ajax => true }

  root 'search#index'
  get ':user' => 'bookmarks#index', as: :user_bookmarks
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name
  validates_presence_of :name, :slug

	has_and_belongs_to_many :bookmarks
	default_scope { order(name: :asc) }

	scope :owned_by, ->(user) { joins(bookmarks: :user).where("bookmarks.user_id = ?", user.id).distinct.order(:name) }

	def should_generate_new_friendly_id?
    name_changed? || super
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	def index
		authorize Tag
		@page = params[:page] ? params[:page] : 1
		@per_page = Kaminari.config.default_per_page
		@tags = Tag.owned_by(current_user).page @page
	end

	def new
		authorize Tag
		@tag = Tag.new
	end

	def create
		authorize Tag
		Tag.create(tag_params)
		redirect_to tags_path
	end

	def edit
		@tag = Tag.friendly.find(params[:id])
		authorize @tag
	end

	def update
		tag = Tag.friendly.find(params[:id])
		authorize tag
		Tag.update(tag, tag_params)
		redirect_to tags_path
	end

	def destroy
		Tag.destroy(params[:id])
		redirect_to tags_path
	end

	def show
		@tag = Tag.friendly.find(params[:id])
		authorize @tag
	end

	def search
		# lock it down for now
		authorize Tag
		# should move this functionality to run directly from the web server ahead of Rails (metal)
		# - needs to accept a second param, exclusion tags from the result (becasue they've been selected/applied already)
		@tags = Tag.where("name LIKE ?", "%#{params[:q]}%")
		respond_to do |format|
			# format.html {render :text => "search: #{params[:q]} => #{@tags.map(&:name)}", status: :ok}
			format.html {render :json => @tags, status: :ok}
			format.js {render :json => @tags, status: :ok}
		end
	end

	private
		def tag_params
			params.require(:tag).permit(:name)
		end
end

app/views/tags/_form.html.slim
=form_for @tag do |f|
	=f.label :name
	=f.text_field :name
	=f.submit

app/views/tags/_search_result_tile.slim
.search-result-tile
	div
		=link_to result.name, result
		=raw("&mdash;")
		=link_to '[edit]', edit_tag_path(result)
		=raw("&mdash;")
		span ="found in #{result.bookmarks.length} bookmarks"

app/views/tags/edit.html.slim
h1 Edit tag
= render 'form'
hr
	=button_to "delete", tag_path(@tag), method: :delete

app/views/tags/index.html.slim
h1 Tags
=link_to "[new tag]", new_tag_path
hr
= paginate @tags
ul
	- @tags.each_with_index do |t, index|
		li
			span =page_counter(@page, @per_page, index, 10)
			=link_to t.name, tag_path(t)
			| &mdash;&mdash;&mdash;
			=link_to '[edit]', edit_tag_path(t)

= paginate @tags

app/views/tags/new.html.slim
h1 Add new tag
= render 'form'

app/views/tags/show.html.slim
h1 ="Tag: #{@tag.name}"
span =button_to 'edit', edit_tag_path(@tag)
hr
- if @tag.bookmarks.length > 0
	ol
		- @tag.bookmarks.each do |b|
			li
				b =link_to "Bookmark: #{b.title}", bookmark_path(b)
				| &mdash;
				=link_to b.url, b.url, target: :new
- else
	p This tag hasn't been used for anything yet.