config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/save" => "bookmarks#save"

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"

  resources :devices do
    resources :browser_windows do
      resources :browser_tabs
    end
  end

  resources :bookmarks, except: [:index, :search]
  get 'bookmarks' => 'bookmarks#index'
  get 'bookmarks_search' => 'bookmarks#search', as: :bookmarks_search

  resources :tags
  get 'tags_search' => 'tags#search', as: :tags_search

  resources :search, only: [:index]
  get '/search/search' => 'search#search', as: :multi_search, :constraints => { :only_ajax => true }

  root 'search#index'
  get ':user' => 'bookmarks#index', as: :user_bookmarks
end

app/models/browser_window.rb
class BrowserWindow < ActiveRecord::Base
	belongs_to :device
	has_many :browser_tabs

	delegate :owner, to: :device
end

app/controllers/browser_windows_controller.rb
class BrowserWindowsController < ApplicationController
	def index
		authorize BrowserWindow
		@browser_windows = BrowserWindow.all
	end

	def show
		@browser_window = BrowserWindow.find(params[:id])
		authorize @browser_window
	end

	def new
		authorize BrowserWindow
		@browser_window = BrowserWindow.new
		@browser_windows = BrowserWindow.all.group_by(&:device)
	end

	def create
		authorize BrowserWindow
		new_window = BrowserWindow.create(browser_window_params)
		Device.find(params[:device_id]).browser_windows << new_window
		redirect_to device_browser_window_path(new_window.device_id, new_window)
	end

	def update
		browser_window = BrowserWindow.find(params[:id])
		authorize browser_window
		browser_window.update!(browser_window_params)
		redirect_to device_browser_window_path(browser_window.device_id, browser_window)
	end

	def edit
		@browser_window = BrowserWindow.find(params[:id])
		authorize @browser_window
		@browser_windows = BrowserWindow.all
	end

	private
		def browser_window_params
      params.require(:browser_window).permit(:name, :private)
    end
end

app/views/browser_windows/edit.html.slim
h1
	span ="Edit Window: #{@browser_window.id} "
	span ="(on #{@browser_window.device.name})"

=form_for @browser_window, url: {action: "update"}, method: 'PUT' do |f|
	=f.label :private
	=f.check_box :private
	=f.submit

hr
h2 Existing Windows
- unless @browser_windows.blank?
	ol
		- @browser_windows.group_by(&:device).each do |device|
			li
				ol
					- device[1].each do |b|
						li
							=link_to device_browser_window_path(b.device, b), data: {'browser-window-id': b.id} do
								span ="Window id: (#{b.id})"
								=" ---- "
								em ="Tabs: (#{b.browser_tabs.count})"
				br

app/views/browser_windows/index.html.slim
h1 Window List
span ="total: #{@browser_windows.length}"
=" | ["
=link_to "create new window", new_device_browser_window_path(device_id: params[:device_id])
="]"
- unless @browser_windows.blank?
	ol
		- @browser_windows.sort.each do |d|
			li
				span private?
				=check_box_tag(:private)
				=link_to device_browser_window_path(d.device_id, d) do
					span id:
					em ="(#{d.id})"
					- tabs = d.browser_tabs
					- unless tabs.blank?
						ol
							- tabs.sort.each do |tab|
								li
									span ="(#{tab.id})"
									span =tab.title

app/views/browser_windows/new.html.slim
h1 Add new browser_window
=form_for @browser_window, url: {action: "create"}, params: {url: 'http://www.google.com', title: 'Google, Yo!'} do |f|
	=f.label :private
	=f.check_box :private
	=f.submit

hr
h2 browser_window List
- unless @browser_windows.blank?
	ol
		- @browser_windows.each do |bw|
			li
				div data-device-id="#{bw[0].id}" ="Device: #{bw[0].name}"
				- unless bw[1].empty?
					ol
						- bw[1].each do |win|
							li
								span private?
								=check_box_tag('private', win.private, win.private)
								=" - "
								=link_to device_browser_window_path(win.device_id, win), data: {'browser-window-id': win.id} do
									span ="window id: "
									em ="(#{win.id})"
									span &mdash; tabs:
								- unless win.browser_tabs.blank?
									div
										| &mdash; tabs
										em =" (#{win.browser_tabs.count}) "
										| &mdash;

									ol
										- win.browser_tabs.each do |tab|
											li
												span tab id:
												em =" 	(#{tab.id}) - "
												span =tab.title

app/views/browser_windows/show.html.slim
h1
	span ="Window: #{@browser_window.id} "
	span ="(on #{@browser_window.device.name})"
span private?
=check_box_tag('private', @browser_window.private, @browser_window.private)
=" - "
=link_to '[Edit]', edit_device_browser_window_path(:device_id => params[:device_id], :id => @browser_window.id)
=" | "
=link_to '[New Window]', new_device_browser_window_path(:device_id => params[:device_id])
=" | "
=link_to '[New Tab]', new_device_browser_window_browser_tab_path(:device_id => params[:device_id], :browser_window_id => params[:id])
hr

h2 ="Window ##{@browser_window.id} Tabs:"
- tabs = @browser_window.browser_tabs
- unless tabs.blank?
	ol
		- tabs.sort.each do |tab|
			li
				=link_to tab.url, data: {'browser-tab-id': tab.id}, target: :new do
					span ="[#{tab.title}] (#{tab.url})"
				=" | "
				=link_to '[Edit]', edit_device_browser_window_browser_tab_path(tab.device, tab.browser_window, tab)