config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/save" => "bookmarks#save"

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"

  resources :devices do
    resources :browser_windows do
      resources :browser_tabs
    end
  end

  resources :bookmarks, except: [:index, :search]
  get 'bookmarks' => 'bookmarks#index'
  get 'bookmarks_search' => 'bookmarks#search', as: :bookmarks_search

  resources :tags
  get 'tags_search' => 'tags#search', as: :tags_search

  resources :search, only: [:index]
  get '/search/search' => 'search#search', as: :multi_search, :constraints => { :only_ajax => true }

  root 'search#index'
  get ':user' => 'bookmarks#index', as: :user_bookmarks
end

app/views/layouts/_main_nav.html.slim
.container
	nav
		div ="Signed in as: #{current_user.try(:email)} - #{current_user.full_name} (#{current_user.username})"
		div =button_to 'Sign out', sign_out_path, method: :delete

		ul.main-nav
			li =link_to 'home', root_path
			li =link_to 'devices', devices_path
			li =link_to 'bookmarks', bookmarks_path
			li =link_to 'tags', tags_path
			li =link_to 'search', search_index_path

	.inline-bookmark-form-container.js-inline-bookmark-form-container
		a.js-inline-bookmark-form-link ="[+] Add Bookmark"

app/views/layouts/application.html.slim
doctype html
html
	head
	  title PersonalBrain
	  =stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
	  =javascript_include_tag 'application', 'data-turbolinks-track' => true
	  =csrf_meta_tags

	body
		.wrapper
			- if signed_in?
				=render partial: '/layouts/main_nav'
			- else
				.container
					nav
						ul.main-nav
							li =link_to 'home', root_path
							li =link_to 'Sign in', sign_in_path

			.container
				#flash
				  - flash.each do |key, value|
				    div class="flash #{key}" =value
				article
					=yield

app/views/layouts/iframe.html.slim
doctype html
html
	head
	  title PersonalBrain Uploader
	  / =stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
	  / =javascript_include_tag 'application', 'data-turbolinks-track' => true
	  =csrf_meta_tags
	  css:
	  	body,
	  	html {
				height: 100%;
				width: 100%;
				margin: 0;
				padding: 0;
				border: 0;
	  	}
	  	body {
				background-color: rgba(0,0,0,0.5);
				position: absolute;
		    top: 0;
		    left: 0;
	  	}
	  	.container {
		  	max-width: 2880px;
		  	margin:0 auto;
	  	}
	  	.panel {
				width: 500px;
				height: 500px;
				margin: 20px auto;
				background-color: #fff;
				text-align: center;
			}


	body
		.container
			#flash
			  - flash.each do |key, value|
			    div class="flash #{key}" =value
			article
				=yield